// Code generated by msgen. You may edit this file.
package main

import (
	"flag"

	"github.com/adm87/msgen/example/server"
	"github.com/adm87/msgen/example/server/generated"
)

type CmdArgs struct {
	Port int
}

func main() {
	args := parseArgs()

	s := generated.NewServer(server.NewExampleServiceController())
	s.SetPort(args.Port)

	if err := s.Start(); err != nil {
		panic(err)
	}
}

func parseArgs() *CmdArgs {
	args := &CmdArgs{
		Port: 8080,
	}

	flag.IntVar(&args.Port, "port", args.Port, "Port to listen on")
	flag.Parse()

	return args
}
