// Code generated by msgen. You may edit this file.
package main

import (
	"flag"

	"github.com/adm87/msgen/example/server"
	"github.com/adm87/msgen/example/server/generated"
)

type ExampleArgs struct {
	Port int
}

func main() {
	args := parseFlags()

	s := generated.NewServer(server.NewExampleServiceController())
	s.SetPort(args.Port)

	if err := s.Start(); err != nil {
		panic(err)
	}
}

func parseFlags() *ExampleArgs {
	args := &ExampleArgs{
		Port: 8080,
	}

	flag.IntVar(&args.Port, "port", args.Port, "Port to run the server on")
	flag.Parse()

	return args
}
