// Code generated by msgen. DO NOT EDIT.
package main

import (
	"github.com/adm87/msgen/example/server"
	"github.com/adm87/msgen/example/server/generated"
)

func main() {
	s := generated.NewServer(server.NewExampleServiceController())

	if err := s.Start(); err != nil {
		panic(err)
	}
}
