// Code generated by msgen. DO NOT EDIT.
package server

import ("github.com/adm87/msgen/example/models")

// ExampleServiceController handles requests for the ExampleService service.
type ExampleServiceController struct {
}

func NewExampleServiceController() *ExampleServiceController {
    return &ExampleServiceController{}
}

func (c *ExampleServiceController) GetUserProfile(userID string)(models.UserProfile, error){
    panic("not implemented")
}

func (c *ExampleServiceController) FilterUserProfiles(age int, country string)([]models.UserProfile, error){
    panic("not implemented")
}