{{- /*
    Generates a disclaimer comment for generated go files
*/ -}}
{{- define "disclaimer.go" -}}
// Code generated by msgen. DO NOT EDIT.
{{- end -}}

{{- /*
    Generates import statements for the given import data
*/ -}}
{{- define "import.statements" -}}
    {{- range $import := . -}}
        {{- if ne $import.Alias "" -}}{{ $import.Alias }} {{ end -}}
        "{{ $import.Path }}"
    {{- end -}}
{{- end -}}

{{- /*
    Formats a field with its name and type
*/ -}}
{{- define "format.field" -}}
{{- if ne .Name "" }}{{ .Name }} {{ end -}}
{{- .Type -}}
{{- end -}}

{{- /*
    Generates parameter list signature for methods
*/ -}}
{{- define "method.signature.parameters" -}}
    {{- range $i, $param := . -}}
        {{- if $i }}, {{ end -}}
        {{- template "format.field" $param -}}
    {{- end -}}
{{- end -}}

{{- /*
    Generates return type signature for methods
*/ -}}
{{- define "method.signature.returns" -}}
    {{- if gt (len .) 1 -}}
        ({{- range $i, $ret := . -}}
            {{- if $i }}, {{ end -}}
            {{- template "format.field" $ret -}}
        {{- end -}})
    {{- else if eq (len .) 1 -}}
        {{- with index . 0 -}}
            {{- template "format.field" . -}}
        {{- end -}}
    {{- end -}}
{{- end -}}