{{- /*
    Generates a disclaimer comment for generated go files
*/ -}}
{{- define "disclaimer.go.noedit" -}}
// Code generated by msgen. DO NOT EDIT.
{{- end -}}

{{- /*
    Generates a disclaimer comment for generated go files that can be edited
*/ -}}
{{- define "disclaimer.go.edit" -}}
// Code generated by msgen. You may edit this file.
{{- end -}}

{{- /*
    Generates import statements for the given import data
*/ -}}
{{- define "import.statements" -}}
    {{- range $import := . -}}
        {{- if ne $import.Alias "" -}}{{ $import.Alias }} {{ end -}}
        "{{ $import.Path }}"
    {{- end -}}
{{- end -}}

{{- /*
    Formats a field with its name and type
*/ -}}
{{- define "format.field" -}}
{{- if ne .Name "" }}{{ .Name }} {{ end -}}
{{- .Type -}}
{{- end -}}

{{- /*
    Generates parameter list signature for methods
*/ -}}
{{- define "method.parameters" -}}
    {{- range $i, $param := . -}}
        {{- if $i }}, {{ end -}}
        {{- template "format.field" $param -}}
    {{- end -}}
{{- end -}}

{{- /*
    Generates return type signature for methods
*/ -}}
{{- define "method.returns" -}}
    {{- if gt (len .) 1 -}}
        ({{- range $i, $ret := . -}}
            {{- if $i }}, {{ end -}}
            {{- template "format.field" $ret -}}
        {{- end -}})
    {{- else if eq (len .) 1 -}}
        {{- with index . 0 -}}
            {{- template "format.field" . -}}
        {{- end -}}
    {{- end -}}
{{- end -}}

{{- /*
    Recursively generates route configuration for the routing tree
*/ -}}
{{- define "configure.routes" -}}
{{- $routes := .routes -}}
{{- $router := .router -}}
{{- $server := .server -}}
{{- $path := .path -}}
{{- range $pathSegment, $node := $routes.Children }}
{{- $routerName := trim $pathSegment "{}" }}
{{ $router }}.Route("/{{ $pathSegment }}", func({{ $routerName }} chi.Router) {
    configureScopedRouter({{ $routerName }}, {{ $server }}, "{{ $path }}/{{ $pathSegment }}")    
    {{- range $method := $node.Methods }}
    {{ $routerName }}.{{ $method.Attributes.Router.Method | pascalCase }}("/", {{ $method.Name }}({{ $server }}))
    {{- end }}
    {{- if gt (len $node.Children) 0 }}
        {{- template "configure.routes" dict "routes" $node "router" $routerName "server" $server "path" (print $path "/" $pathSegment) -}}
    {{- end }}
})
{{- end }}
{{- end -}}