// Code generated by msgen. You may edit this file.
package server

import (
	"github.com/adm87/msgen/example/models"
)

type ExampleServiceController struct {
	// Add fields as necessary
}

func NewExampleServiceController() *ExampleServiceController {
	return &ExampleServiceController{
		// Initialize fields as necessary
	}
}

func (c *ExampleServiceController) Startup() error {
	// Implement startup logic here
	return nil
}

func (c *ExampleServiceController) Shutdown() error {
	// Implement shutdown logic here
	return nil
}

func (c *ExampleServiceController) CreateUserProfile(user models.CreateUserRequest) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) DeleteUserProfile(userID string) error {
	panic("not implemented")
}

func (c *ExampleServiceController) UpdateUserProfile(userID string, user models.UserProfile) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) GetUserProfile(userID string) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) FilterUserProfiles(age int, country string) ([]models.UserProfile, error) {
	panic("not implemented")
}
