// Code generated by msgen. You may edit this file.
package server

import (
	"github.com/adm87/msgen/example/models"
	"github.com/adm87/msgen/example/server/generated/ctx"
)

type ExampleServiceController struct {
	// Add fields as necessary
}

func NewExampleServiceController() *ExampleServiceController {
	return &ExampleServiceController{
		// Initialize fields as necessary
	}
}

func (c *ExampleServiceController) CreateUserProfile(ctx *ctx.Context, user models.CreateUserRequest) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) DeleteUserProfile(ctx *ctx.Context, userID string) error {
	panic("not implemented")
}

func (c *ExampleServiceController) UpdateUserProfile(ctx *ctx.Context, userID string, user models.UserProfile) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) GetUserProfile(ctx *ctx.Context, userID string) (models.UserProfile, error) {
	panic("not implemented")
}

func (c *ExampleServiceController) FilterUserProfiles(ctx *ctx.Context, country string) ([]models.UserProfile, error) {
	panic("not implemented")
}
